### ISSUE TITLE
API requests blocked

### ISSUE THREAD

**Issue by gendai** [henrydatei/upland.me-api#2]
Hi,

I know this repo is relatively outdated but it seems that the requests to the API are now blocked by Cloudflare. I'm always getting this error:
`requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.upland.me/authentication`
Is there any known workaround ? Thanks !

**Comment by henrydatei** [comment]
I don't know any workaround but as far as I remember, when logging in you have to answer a Google ReCaptcha. This might be the reason. 

An other alternative would be that the api endpoint has changed. You can check this by opening the development tools in your browser and see what's going on in the network tab when logging in. Maybe you will spot something that belongs to the login-process.

**Comment by gendai** [comment]
Got it, I'm currently giving a try to [https://github.com/Anorov/cloudflare-scrape](https://github.com/Anorov/cloudflare-scrape), which might help to bypass the cloudflare check.
Thanks for the quick reply!
